apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: fe-deploy 
  labels: 
    name: fe-deploy 
    app: bc16-app 
spec: 
  selector: 
    matchLabels: 
      name: frontend-pod 
      app: bc16-app 
  template: 
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: bc16-app
    spec:
      containers:
      - name: postgres
        image: rishmitha/fe_new1
        ports:
        - containerPort: 80
