apiVersion: apps/v1
kind: Deployment
metadata:
  name: org-deploy
  labels:
    name: org-deploy
    app: bc16-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: org-pod
      app: bc16-app
  template:
    metadata:
      name: org-pod
      labels:
        name: org-pod
        app: bc16-app
    spec:
      containers:
      - name: postgres
        image: rishmitha/orgsvc
        ports:
        - containerPort: 8081
        env: 
          - name: "SPRING_DATASOURCE_URL"
            value: "jdbc:postgresql://db:5432/postgres"
          - name: "SPRING_DATASOURCE_USERNAME"
            value: "postgres"
          - name: "SPRING_DATASOURCE_PASSWORD"
            value: "1234"
          - name: "SPRING_JPA_HIBERNATE_DDL_AUTO"
            value: "update" 