apiVersion: v1 
kind: Service 
metadata: 
  name: fe-service 
  labels: 
    name: fe-service
    app: bc16-app 
spec: 
  type: NodePort 
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: 
    name: frontend-pod 
    app: bc16-app
