apiVersion: v1
kind: Service
metadata:
  name: job-service
  labels:
    name: job-service
    app: bc16-app
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    name: job-pod
    app: bc16-app