apiVersion: v1
kind: Service
metadata:
  name: organization-service
  labels:
    name: organization-service
    app: bc16-app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    name: org-pod
    app: bc16-app