apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: bc16-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: bc16-app