apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: bc16-app
spec:
  containers:
    - name: postgres
      image: rishmitha/fe_new1
      ports:
        - containerPort: 80
