apiVersion: v1
kind: Pod
metadata:
  name: job-pod
  labels:
    name: job-pod
    app: bc16-app
spec:
  containers:
    - name: postgres
      image: rishmitha/jobsvc
      ports:
        - containerPort: 8082
