apiVersion: v1
kind: Pod
metadata:
  name: org-pod
  labels:
    name: org-pod
    app: bc16-app
spec:
  containers:
    - name: postgres
      image: rishmitha/orgsvc
      ports:
        - containerPort: 8081
